### ISSUE TITLE
[question] Does AMENT_IGNORE cause vcs to ignore repos?

### ISSUE THREAD

**Issue by jacquelinekay** [ament/ament_tools#103]
When I do a `vcs list` on my workspace I notice that repositories with AMENT_IGNOREs do not get listed. That's actually really convenient, although I'm kind of confused about why it happens because I thought ament and vcstool were different tools that weren't aware of each other.

**Comment by wjwwood** [comment]
Searching the `vcstool` code (https://github.com/dirk-thomas/vcstool) I don't see that it checks for that. I also don't see the same behavior on my machine, though I didn't try too many different situations to try and make it happen.

**Comment by dirk-thomas** [comment]
`vcstool` knows nothing about `ament` (the same the other way around). So I don't think the marker file has any effect.

Please try to provide a reproducible sequence of commands which demonstrate your use.

**Comment by dirk-thomas** [comment]
I will close this for now. If you happen to experience this again please reopen it with a reproducible example.
