### ISSUE TITLE
need to source build dependencies for ament-python build type

### ISSUE THREAD

**Issue by mikaelarguedas** [ament/ament_tools#109]

**Comment by dirk-thomas** [comment]
This seems to be already the case: see https://github.com/ament/ament_tools/blob/711fa60ffaa711d5d4f26ea5bcef6e794bfd9cae/ament_tools/build_types/ament_python.py#L152

Can you please provide a reproducible example.

**Comment by dirk-thomas** [comment]
Might it be related to the introspection of the setup file before the actual build is happening? Triggered by this line https://github.com/ament/ament_tools/blob/711fa60ffaa711d5d4f26ea5bcef6e794bfd9cae/ament_tools/build_types/ament_python.py#L470

**Comment by mikaelarguedas** [comment]
TBH that was a long time ago, I don't really remember. I think that I needed to source manually rclpy otherwise I could not build the executables of https://github.com/ros2/examples/issues/127 (because setup.py was calling some rclpy functions)

**Comment by clalancette** [comment]
@mikaelarguedas Since the upstream PR was merged, can this be closed?

**Comment by wjwwood** [comment]
@dirk-thomas when you get a chance, can this be merged? (@mikaelarguedas said to ask you)
