### ISSUE TITLE
Robustness to double `--` delimiters

### ISSUE THREAD

**Issue by dhood** [ament/ament_tools#111]
`--` can be used to signal the end of a "catch all" argument group when invoking ament from the command line.

It's possible that, when command line arguments are being built up programmatically for example, the delimiter is added twice. This currently isn't handled.

```
$ ament build . --force-cmake-configure --cmake-args -DCMAKE_BUILD_TYPE=Debug -- -- --ament-cmake-args -DCMAKE_BUILD_TYPE=Release
usage: ament [-h]
             [uninstall_pkg | test_pkg | package_version | uninstall | test_results | build | list_packages | build_pkg | package_name | test]
             ...
ament: error: unrecognized arguments: --
```

**Comment by dirk-thomas** [comment]
If the caller if careful about constructing the command line this should never happen. A simple strategy could be wherever concatenation happens it either always appends `--` when necessary or always prepends it (but doesn't mix both approaches).

Therefore I don't think this package needs to handle this case and I would close this as "wontfix".
