### ISSUE TITLE
install error on windows

### ISSUE THREAD

**Issue by Karsten1987** [ament/ament_tools#112]
I constantly get this error at last on my ament build. I guess, `ament build` tries to overwrite the same `ament.exe` which is currently used.

```
Installing ament.exe script to c:\dev\ros2_src\install\bin
error: [Errno 13] Permission denied: 'c:\\dev\\ros2_src\\install\\bin\\ament.exe
```

The build is fine though.

**Comment by dirk-thomas** [comment]
This implies that you did the following in the same shell which is generally not recommended:

* build a set of packages (including `ament_tools`)
* source the setup file in the generated install prefix
* build the workspace again
