### ISSUE TITLE
Add ability for ament to list the dependencies of a given package

### ISSUE THREAD

**Issue by dhood** [ament/ament_tools#113]
**Context:**
ament infers the dependencies of packages in order to build a workspace with multiple packages in the right order. While the Python API of `ament_package` already exposes the information about a package’s dependencies, there is currently no command line option for `ament` for outputting the information (see https://github.com/ament/ament_tools/issues/107).

**Pointers:**
- [the `ament_package` API](https://github.com/ament/ament_package)
- [the other verbs in `ament_tools`](https://github.com/ament/ament_tools/tree/master/ament_tools/verbs)

**Comment by mikaelarguedas** [comment]
Claimed by @rolling-robot
