### ISSUE TITLE
changing ament install prefix doesn't change the cmake install prefix

### ISSUE THREAD

**Issue by dhood** [ament/ament_tools#119]
If I install to a particular location, delete it, and then install to a different location, cmake is still trying to install to the first location.

It will install to the second location if I add `--force-cmake-configure`, but I feel like it's not really "expected behaviour" that this is not triggered automatically.

Note that this means that sourcing the setup file of the second install fails with:
```
dhood@osrf-esteve:~/ros2_test_ws [ros2_test_ws]$ source install_2/setup.bash 
Traceback (most recent call last):
  File "/home/dhood/ros2_test_ws/install_2/_order_packages.py", line 72, in <module>
    main()
  File "/home/dhood/ros2_test_ws/install_2/_order_packages.py", line 38, in main
    package_names = [d for d in os.listdir(path)]
FileNotFoundError: [Errno 2] No such file or directory: '/home/dhood/ros2_test_ws/install_2/share/ament_index/resource_index/packages'
```

**Comment by dirk-thomas** [comment]
Please try if #120 fixes the problem.

**Comment by dhood** [comment]
yes, it does. thanks for looking at it
