### ISSUE TITLE
uninstalling after installing to a different directory

### ISSUE THREAD

**Issue by dhood** [ament/ament_tools#121]
uninstalling only works if it's invoked passing the same install prefix. Is that the expected behaviour?

So, after `ament build --install-space install1` I have to call `ament uninstall --install-space install1`

If it is the expected behaviour, I think we should be more carefull about removing the `install.log` [here](https://github.com/ament/ament_tools/blob/a0bada4e507b8564326f5f07045ec22e28083f96/ament_tools/build_types/ament_python.py#L386). Always deleting it means that after calling `ament uninstall` which doesn't uninstall anything, if I later call `ament uninstall --install-space install1` nothing will happen

**Comment by dirk-thomas** [comment]
I would say yes. The tool has no knowledge about the previous location so it wouldn't know where to uninstall from (if not from the currently specified install space).

**Comment by dhood** [comment]
I think in the case of python packages, it does know:

```
dhood@osrf-esteve:~/ros2_test_ws [ros2_test_ws]$ cat build/dummy_package/install.log 
/home/dhood/ros2_test_ws/install1/lib/python3.5/site-packages/dummy_package-0.0.0-py3.5.egg-info/dependency_links.txt
/home/dhood/ros2_test_ws/install1/lib/python3.5/site-packages/dummy_package-0.0.0-py3.5.egg-info/SOURCES.txt
/home/dhood/ros2_test_ws/install1/lib/python3.5/site-packages/dummy_package-0.0.0-py3.5.egg-info/top_level.txt
/home/dhood/ros2_test_ws/install1/lib/python3.5/site-packages/dummy_package-0.0.0-py3.5.egg-info/requires.txt
/home/dhood/ros2_test_ws/install1/lib/python3.5/site-packages/dummy_package-0.0.0-py3.5.egg-info/PKG-INFO
```

but because of [this check that uses the install prefix of the current context](https://github.com/ament/ament_tools/blob/a0bada4e507b8564326f5f07045ec22e28083f96/ament_tools/build_types/ament_python.py#L375), the files will not be removed, but the `install.log` will be removed

**Comment by dirk-thomas** [comment]
This line prevents the tool from touching `install1` if you have passed `install2` in the current invocation. I am not sure that the tool should uninstall anything from `install1` when the user invoked it with `install2`. Maybe it should just error out in that case and let the user know about the inconsistency?

**Comment by dhood** [comment]
OK, I agree with you about not touching `install1` if invoked with `install2` (this doesn't extend to if I installed to `install2/install1`, but that's a different point).

The main concern I have is that I think we should not remove the log in the case that the install prefix doesn't match. Otherwise, if I do:

```
ament build --install-space install1
ament uninstall  # oops, package not uninstalled
ament uninstall --install-space install1 # nothing uninstalled because `install.log` is gone
```
the uninstall process loses its references to the installed files

**Comment by dirk-thomas** [comment]
Closing since the repo is archived.
