### ISSUE TITLE
We should validate ament_cmake packages after installation

### ISSUE THREAD

**Issue by rohbotics** [ament/ament_tools#129]
Make sure they actually install package.xml, etc

**Comment by wjwwood** [comment]
I might also be useful to suggest the reason behind the issue you ran into, something like:

```
Package 'foo' did not install some required files for an 'ament_cmake' package type:
  - '<prefix>/share/foo/package.xml' was found
  - '<prefix>/share/ament_index/resource_index/packages/foo' is missing
[ ... ]

Did you forget to call `ament_package()` in your `CMakeLists.txt`?
```

**Comment by dirk-thomas** [comment]
I can see certain packages could be skipping the `ament_package()` call if e.g. a required dependency is not available (as a graceful fallback for example). In that case the warning would be annoying since it is intended.

**Comment by wjwwood** [comment]
Well, lots of our code assumes that a package file in the ament resource, and potentially other things, so if we don't enforce this we'll have undo those assumptions. For example, @rohbotics' problem was that he had a workspace with only a pair of `ament_cmake` built type packages, neither of which actually called `ament_package()` and so the setup file crashed trying to `ls` the `share/ament_index/.../packages` folder.

**Comment by wjwwood** [comment]
That would probably also be a problem if the workspace was empty.

**Comment by rohbotics** [comment]
In an empty workspace `ament build` does nothing, no setup.bash is created

```
rohan@machina:~/test_ws$ ls src
rohan@machina:~/test_ws$ ament build
# Topological order
All selected packages are being skipped. Nothing to do.
rohan@machina:~/test_ws$ ls
src
rohan@machina:~/test_ws$
```

**Comment by dirk-thomas** [comment]
Closing since the repo is archived.
