### ISSUE TITLE
assert that ament_cmake packages register in the ament_index

### ISSUE THREAD

**Issue by wjwwood** [ament/ament_tools#136]
This would catch scenarios where an `ament_cmake` package (as declared in the `package.xml`'s `<export><build_type>...` section) but the user did not call `ament_package()` in cmake.

Basically the tool would just check that the file `<prefix>/share/ament_index/resource_index/packages/<package name>` exists after completing the install step.

**Comment by dirk-thomas** [comment]
This looks like a duplicate of #129.

**Comment by wjwwood** [comment]
Hmm, I looked for that exact issue and didn't find it. Thanks.
