### ISSUE TITLE
No setup.bash for --isolated compilation

### ISSUE THREAD

**Issue by Karsten1987** [ament/ament_tools#138]
There is currently no `setup.bash` file created when compiling with `--isolated`. There is only a `local_setup.bash` which makes chaining workspaces more clumsy. 
Both files are generated when compiling without isolation.

**Comment by dirk-thomas** [comment]
I just dumped my local prefix-level setup files for isolation here: https://github.com/ament/ament_package/tree/isolated_prefix_level_setup I haven't touched since the original development but maybe they are a good start for this.

**Comment by dirk-thomas** [comment]
Closing since the repo is archived.
