### ISSUE TITLE
option to build only a package and its dependencies

### ISSUE THREAD

**Issue by mikaelarguedas** [ament/ament_tools#155]
discussed in the past (e.g. https://github.com/ament/ament_tools/pull/114#issuecomment-258572094).
Implementing a `--deps` flag resulting in building the dependency of package(s) specified with `--only`

**Comment by gaoethan** [comment]
what does this mean ? how about making it by just give "the target one package" to the current --only-packages ?

**Comment by mikaelarguedas** [comment]
What I mean by this is that right now `--only-packages` builds only the packages you specify explicitly but not the packages it depends on.
If I have a package `foo` that depends on `bar` and run `ament build --only-packages foo` it will build only `foo` and **not** `bar`. A flag such as the described `--deps` would allow to run `ament build --only-packages foo --deps` resulting in building `foo` and `bar`.

On such a simple example it doesnt seem much overhead to run  `ament build --only-packages foo bar` but for packages having dozens of dependencies that is inconvenient.

**Comment by gaoethan** [comment]
yeah, it doesn't make sense in the case of dozens of dependent packages given to "--only-packages".
you know, a package has several types of dependency like the following:
buildtool_depend
build_export_depend
build_depend
exec_depend
depend
test_depend and so on
so... what type of dependency should be taken into account to use for option "--deps"? 

Actually, there is some package repeated in the above "depend" tag and it's necessary to sort out the final. BTW, it seems that it's direct to get the final from the maker file of resource type "package_run_dependencies" :).
Furthermore, each dependent package also has its own dependency to the other packages, it's recursive. it's also possible that a package and the dependence of its dependent package has some common dependency, what's your suggestion to manage and finalize the pure dependency ?

**Comment by mikaelarguedas** [comment]
> Furthermore, each dependent package also has its own dependency to the other packages, it's recursive. it's also possible that a package and the dependence of its dependent package has some common dependency, what's your suggestion to manage and finalize the pure dependency ?

The build tool already has the ability of parsing all the `package.xml`, walking all the recursive dependencies and [construct the order](https://github.com/ament/ament_tools/blob/d0aa74da899c0f15efe1c3087970121f09f9460c/ament_tools/topological_order.py#L32) in which they should be built.

So if we extend our previous example:
package `foo` depends on `bar` and `baz` and package `bar` also depends on `baz` so the resulting topological order will be `baz` -> `bar` -> `foo` and they cannot be built in parallel.

If `bar` also depends on package `X`:
`baz` and `X` can be built in parallel and the build of `bar` cannot start until both `X` ans `baz` completed.


The current behavior of `ament build --only foo` builds only `foo`
The current behavior of `ament build --end-with foo` will build every package in the topological order until it reaches `foo`

The suggested `--deps` flag will just take the branch of the dependency tree where `foo` is the leaf and build everything on that branch in order

**Comment by dirk-thomas** [comment]
Please keep in mind that we are currently not planning to support `ament_tools` in the mid/long term future. Instead the goal is to work towards a single generic build tool to consolidate the different separate tools used in ROS (see [design article](http://design.ros2.org/articles/build_tool.html)). I just want to make you aware of this before spending significant effort on feature development for `ament_tools`.

**Comment by dirk-thomas** [comment]
Closing since the repo is archived.
