### ISSUE TITLE
Build of package on windows hangs sometimes

### ISSUE THREAD

**Issue by firesurfer** [ament/ament_tools#157]
I sometimes have the problem that a build on windows of a package hangs. I can then press STRG + C and it continues compilation.

The last package I had this problem was this one: https://github.com/firesurfer/rclcs_testing_ws/blob/master/src/test_cpp/CMakeLists.txt
It uses a fairly old syntax but still compiles fine. I also had this problem on some packages of the ros2 sources.

**Comment by dirk-thomas** [comment]
Can you please describe what you mean with "hangs" and/or copy the console output into this ticket.

Might this be a duplicate of #145?

**Comment by firesurfer** [comment]
My windows 10 installtion just totaly destroyed itself. Unfortunatly due to the exams I won't find any time soon to do a new windows setup. In case I'll see this bug again I'll reopen this issue.
