### ISSUE TITLE
Test Report Generation for ament test tools

### ISSUE THREAD

**Issue by sagniknitr** [ament/ament_tools#179]
Is there any tool currently in ament which can generate a report document (.pdf,.xls etc.)  for the test results ? I want some help in this area.

**Comment by dirk-thomas** [comment]
`ament test` only provides a text summary of the test results. It actually parses the xUnit result files itself and outputs the bare numbers. I would suggest you look into tools which can read xUnit result files and can generate the report format you like.

**Comment by sagniknitr** [comment]
Ok...thanks @dirk-thomas ..I am closing this issue
