### ISSUE TITLE
Add custom logger to msbuild

### ISSUE THREAD

**Issue by wjwwood** [ament/ament_tools#20]
I did some research last night about getting colors out of `msbuild` since the output is really hard to read without it. But the best solution I could come up with is to make a custom logger for `msbuild` which outputs ANSI escape sequences rather than the normal Windows color system.

Combining this with the ANSI Jenkins plugin which I've already tested, should work nicely. Test is here:

http://54.183.26.131:8080/job/testing_ansi/10/console

Basically, `ament build` would need to build and provide the custom logger (a C# library) and pass it to `msbuild`. Here is a library someone put together that does just that:

https://github.com/abe545/strider-msbuild-logger/blob/5e64c710fcda3db7f9ae009f18a764216d5efb89/Logger.cs

AC:
- [ ] `ament build` builds this library if on Windows and then passes it to the invocations of `msbuild`.
- [ ] `msbuild` outputs ANSI escape sequences for colored text, allowing Jenkins or Cmder to process it.

This is obviously super low priority, but would be nice to have at some point.

**Comment by dirk-thomas** [comment]
Closing since the repo is archived.
