### ISSUE TITLE
Replace custom flake8 style check with ament_pep8 and ament_pyflakes

### ISSUE THREAD

**Issue by wjwwood** [ament/ament_tools#22]
Once ament/ament_lint#11 is resolved update this package to use the newly split up tools.

AC:

- [x] This package tests it styles using `ament_pep8` and `ament_pyflakes`.

**Comment by dirk-thomas** [comment]
@esteve @tfoote @wjwwood Please review the referenced PR.

**Comment by wjwwood** [comment]
+1
