### ISSUE TITLE
build prefix command is naive

### ISSUE THREAD

**Issue by wjwwood** [ament/ament_tools#57]
This function:

https://github.com/ament/ament_tools/blob/master/ament_tools/build_types/cmake.py#L346-L364

Currently sources dependencies of the package being built in an arbitrary order if they have a `local_setup.*` file.

Instead it should source the `local_setup.*` files for the recursive build dependencies and they should be sourced in topological order.

**Comment by dirk-thomas** [comment]
`build_dependencies` in this context are **not** the direct build dependencies of the package specified in the manifest. This list already contains all recursive dependencies in topological order.

Therefore I don't think anything needs to be changed here?

**Comment by dirk-thomas** [comment]
Based on the output of #62 it looks like that the order is correct. The problem is that the environment files include not only the recursive dependencies but also upstream packages - basically all packages of the workspace.

**Comment by wjwwood** [comment]
@dirk-thomas But they should be skipped because they don't have environment hooks inside the workspace? or is it a problem when you install two workspaces to the same install space?

**Comment by dirk-thomas** [comment]
Sorry, I meant downstream packages. E.g. `ament_cppcheck` doesn't have any dependencies but currently uses the environment of all packages in the workspace (which is only the case when rebuilding a workspace again).

**Comment by wjwwood** [comment]
Oh, it's not just the dependencies, but also anything that comes before in the topological order.

**Comment by dirk-thomas** [comment]
It includes even packages which come *afterwards* in the topological order.

**Comment by dirk-thomas** [comment]
For packages with dependencies on other ament packages the list and order is correct. But for packages without dependencies on other ament packages the list contains *all* packages from the workspace. The fix is simple: #63.
