### ISSUE TITLE
provide build only environment hooks

### ISSUE THREAD

**Issue by wjwwood** [ament/ament_tools#76]
I'm putting this into a ticket so we can remember it, but I don't think we need it right now.

---

Basically we make a distinction in `ament` between run environment variables and build environment variables but only provide a mechanism to extend the run environment variables.

Run environment variables are set after building a package and are necessary to "use" it, i.e. run things built by it. Examples include the `PATH`, the `[DY]LD_LIBRARY_PATH`, and the `PYTHONPATH`.

Build environment variables are set after building a package and are needed to build something else on top of that package. Examples include the `CMAKE_PREFIX_PATH` and the `PKG_CONFIG_PATH`.

Since building on a package may require running something from that package, the build environment variables would also include the run environment variables.

We allow packages to extend the run environment through the use of environment hooks which get sourced when those packages are going to be used, either by the build tool before building on top of those packages, or by the user when they source a `local_setup.*sh` or a `setup.*sh`. However, for build specific modifications to the environment there is no pattern for doing this on a per package basis. An example of this variable is the `CMAKE_PREFIX_PATH` which is not set by our setup files but is rather injected by the build tool during the build process, e.g.: https://github.com/ament/ament_tools/blob/release-alpha3/ament_tools/build_types/cmake.py#L376-L377

In my opinion there are three downsides to setting these build only environment variables in the tool rather than through a build specific environment hook of the package:
- There is no way for a package to extend the variables set beyond its build type.

For example, if a package needs to be on the `CMAKE_PREFIX_PATH` and it needs to be on the `PKG_CONFIG_PATH` in order to built on, then it would have a problem because it would only be on the `CMAKE_PREFIX_PATH` by default. In order to extend the `PKG_CONFIG_PATH` it would need to use a run environment hook. This isn't really an issue, but it's not conceptually consistent because we have a distinction between build and run time environment changes, but you can only extend one of them.
- There is no way to build on top of a workspace with out the build tool or a manual step for the user.

Consider you built a workspace with `ament build` and then you wanted to build a single CMake package by hand on top of that (`find_package`'ing something in the workspace). After sourcing the `setup.*sh` file of the workspace, your single package would fail because the workspace is not on the `CMAKE_PREFIX_PATH`. This is the case because currently workspace prefixes are added to the `CMAKE_PREFIX_PATH` by the build tool. So you need to manually extend the `CMAKE_PREFIX_PATH` in order to build your single package. It happens that you can just extend it with the `AMENT_PREFIX_PATH`, but that's not an obvious step and if we move beyond just CMake packages in the workspace a potentially more complex step.

This usability issue is what lead me to think about and suggest this enhancement.
- The current method over exposes workspaces to build variables like the `CMAKE_PREFIX_PATH`.

Because of the logic here:

https://github.com/ament/ament_tools/blob/release-alpha3/ament_tools/build_types/cmake.py#L376-L377

Every workspace prefix on the `AMENT_PREFIX_PATH` gets added to the `CMAKE_PREFIX_PATH`, even if those workspaces do not contain CMake packages. This commonly happens when doing an isolated build where every package is installed to its own workspace. For example, sourcing the `local_setup.sh` of an isolated build yields a `AMENT_PREFIX_PATH` with a separate entry for each package, and so adding the `AMENT_PREFIX_PATH` in whole to the `CMAKE_PREFIX_PATH` unnecessarily adds folders which do not contain CMake packages. Again this isn't a big issue in practice, but it is not conceptually consistent and it might hide subtle bugs by putting packages on the `CMAKE_PREFIX_PATH` that shouldn't be.

---

My proposal is two fold:
- First introduce build only environment hooks for packages.

These would work just like normal environment hooks except they would not get sourced by `local_setup.sh`, but instead would get sourced by a new `local_build_setup.sh`. This would also mean that in order to use a workspace (just run things out of it) you'd continue to source the `setup.*sh` file in the root of the workspace, but to build on top of it you'd source the `build_setup.*sh` file which would source the `setup.*sh` file as well as do any package specific work needed to build on top of the packages in the workspace. The availability of the `build_setup.*sh` files would, in my opinion, address the usability issue described in the 2nd point from above.

These would allow packages to extend their build environment in arbitrary ways on a per package basis, which addresses both issues 1 and 3 from above.
- Use this feature in the build tool rather than manually extending certain variables within the build tool based only on the build type.

For example:
- https://github.com/ament/ament_tools/blob/release-alpha3/ament_tools/build_types/cmake.py#L350-L351
- https://github.com/ament/ament_tools/blob/release-alpha3/ament_tools/build_types/cmake.py#L376-L377

---

Like I said, this isn't necessary right now, but I just wanted to capture the idea in case we want to do it in the future. Hopefully it is complete enough that someone could pick it up and run with it.

**Comment by dirk-thomas** [comment]
Closing since the repo is archived.
