### ISSUE TITLE
Errors when passing multiple parameters to ament build

### ISSUE THREAD

**Issue by dhood** [ament/ament_tools#83]
```
ament build . --cmake-args -DCMAKE_BUILD_TYPE=Release --force-cmake-configure
```

gives 

```
$ ament build . --cmake-args -DCMAKE_BUILD_TYPE=Release --force-cmake-configure
# Topological order
 - rcl

Process package 'rcl' with context:
--------------------------------------------------------------------------------
 source_space => /home/dhood/ros2_ws/src/ros2/rcl/rcl
  build_space => /home/dhood/ros2_ws/src/ros2/rcl/rcl/build/rcl
install_space => /home/dhood/ros2_ws/src/ros2/rcl/rcl/install
   make_flags => -j4, -l4
  build_tests => False
--------------------------------------------------------------------------------
+++ Building 'rcl'
Running cmake because arguments have changed.
==> '. /home/dhood/ros2_ws/src/ros2/rcl/rcl/build/rcl/cmake__build.sh && /usr/bin/cmake /home/dhood/ros2_ws/src/ros2/rcl/rcl -DCMAKE_BUILD_TYPE=Release --force-cmake-configure -DCMAKE_INSTALL_PREFIX=/home/dhood/ros2_ws/src/ros2/rcl/rcl/install' in '/home/dhood/ros2_ws/src/ros2/rcl/rcl/build/rcl'
CMake Error: The source directory "/home/dhood/ros2_ws/src/ros2/rcl/rcl/build/rcl/--force-cmake-configure" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.

<== Command '. /home/dhood/ros2_ws/src/ros2/rcl/rcl/build/rcl/cmake__build.sh && /usr/bin/cmake /home/dhood/ros2_ws/src/ros2/rcl/rcl -DCMAKE_BUILD_TYPE=Release --force-cmake-configure -DCMAKE_INSTALL_PREFIX=/home/dhood/ros2_ws/src/ros2/rcl/rcl/install' failed with exit code '1'
```

At https://github.com/ament/ament_tools/blob/release-alpha4/ament_tools/build_types/cmake.py#L78, the value of `cmake_args` is `['-DCMAKE_BUILD_TYPE=Debug', '--force-cmake-configure']`. I understand that this is the expected performance of `extract_argument_group`, so maybe it's just user error on my part, but I wouldn't have expected to need to invoke 
```
ament build_pkg . --cmake-args -DCMAKE_BUILD_TYPE=Debug -- --force-cmake-configure
```
with the extra delimiter

**Comment by jacquelinekay** [comment]
The second command (`ament build_pkg . --cmake-args -DCMAKE_BUILD_TYPE=Debug -- --force-cmake-configure`) is the "correct" way of entering an argument group to `--cmake-args`.  It sounds like you're expecting `extract_argument_group` to find the next delimiter for you. 

I think this convention for disambiguating arguments is fairly common, although I would ask @wjwwood for more information about why this method for argument parsing was chosen. I think the main reason for requiring the extra delimiter is if ament and CMake happen to accept some of the same flags, then it's ambiguous which flags after `--cmake-args` are being passed to ament and which are passed to CMake.

**Comment by dirk-thomas** [comment]
This is a common limitation of argparse. To avoid the extra delimiter you can pass all other arguments *before* "catch all" options like --cmake-args.

So in your case the following will work:

    ament build . --force-cmake-configure --cmake-args -DCMAKE_BUILD_TYPE=Release

If nobody objects I would close this as `wontfix` since there is nothing we can do to change how `argparse` works.

**Comment by dhood** [comment]
Ok, thanks for the info
I guess it took me by surprise because the majority of time I had been passing multiple arguments without a problem.

I realise now that I must have just been 'lucky' in the sense that I wasn't using an argument that `extract_argument_group` ever detected, or that when I was, that argument group was at the end (indeed `ament build . --force-cmake-configure --cmake-args -DCMAKE_BUILD_TYPE=Debug` works fine).

Probably no need to keep this issue open then - documentation will explain it one day if not already and I just missed it. I might add a bit to the 'Tips' section of https://github.com/ros2/ros2/wiki/Ament-Tutorial if I've understood the situation correctly

**Comment by dhood** [comment]
thanks @dirk-thomas, didn't see that you had already replied. I've edited the tutorial.

**Comment by wjwwood** [comment]
Well we could change it so that `ament build . --cmake-args -DCMAKE_BUILD_TYPE=Debug --force-cmake-configure` would work, by closing the `--cmake-args` list of arguments whenever `--` OR any known command line arguments are encountered, but that would make it impossible to pass `--force-cmake-configure` as an option to CMake via the `--cmake-args`, which is obviously not desired, but there are other less obvious arguments that might exist for both, e.g. `-v` or something like that.

I agree there's nothing to change here other than documentation.

**Comment by wjwwood** [comment]
For what it's worth this is mentioned in the `-h`:

```
  --cmake-args [CMAKE_ARGS [CMAKE_ARGS ...]]
                        Arbitrary arguments which are passed to all CMake
                        projects. Argument collection can be terminated with
                        '--'.
```

But I understand that it isn't immediately obvious.

**Comment by wjwwood** [comment]
The tutorial changes lgtm, thanks @dhood. I'll close this for now, but feel free to continue discussion and we can reopen if necessary.
