### ISSUE TITLE
[cmake] use `cmake --build` rather than calling `make` or `msbuild` directly

### ISSUE THREAD

**Issue by wjwwood** [ament/ament_tools#88]
There are a few complications with this, such as passing "make arguments" through `cmake --build` (when using `make`), but I think it will make our tools more flexible.

**Comment by ahundt** [comment]
Thanks!

**Comment by jpgr87** [comment]
`cmake --build` allows you to [pass flags to the native tool](https://cmake.org/cmake/help/v3.9/manual/cmake.1.html#build-tool-mode) by using a `--` on the command line.  Is that what you mean for passing "make arguments"?

**Comment by wjwwood** [comment]
@jpgr87 yes that's what I was talking about. I meant it just means that only part of the build command is portable, which the point of this was, i.e. don't assume make or ninja or msbuild. But since the parallelization flags are not portable you still need to know which you are using so you know which flags to pass cmake. So "just using `--build`" doesn't remove any need to parse and know which cmake generator you used.

**Comment by ahundt** [comment]
@wjwwood am I correct that `cmake --build` would assist with building when using generators that aren't via a hard coded command? If you don't care about the parallelization flags that's useful.

I don't really have context for the prior conversation, so apologies if my comment is nonsensical. :-)

**Comment by dirk-thomas** [comment]
@ahundt We will hopefully get back to switching to a universal build tool and will not continue to support `ament_tools`. I just wanted to mentioned this before your are considering to spend significant effort on improving it. My current prototype of the new build tool already uses `cmake --build` and supports different generators.

**Comment by ahundt** [comment]
Awesome! FYI if you're reconsidering options for a universal build tool, homebrew has improved dramatically over the last year and a half and now supports Linux, has more a more OS agnostic backend, and has solved the major issues with multiple versions of the same project. Perhaps the effort for adding windows would be low enough bar and then homebrew could meet your goals?

- https://github.com/Homebrew/brew/releases/
- https://github.com/Linuxbrew/brew/issues/1

No worries if it still does not make sense to use homebrew. :-)

**Comment by wjwwood** [comment]
> If you don't care about the parallelization flags that's useful.

But we do 😛.

**Comment by dirk-thomas** [comment]
Closing since the repo is archived.
