### ISSUE TITLE
test timeout not getting triggered in ament_python package

### ISSUE THREAD

**Issue by dhood** [ament/ament_tools#97]
If I have an `ament_cmake` package with python tests, if they take too long they timeout and get killed by ctest.

If the same test is being called from within an `ament_python` package, I can't get the timeout to trigger.

See for example [this dummy package](https://github.com/dhood/dummy_package): changing [this line](https://github.com/dhood/dummy_package/commit/776a4c13e6b15ba4f84a038c910d1917aafb204f#diff-8effae99ed5096ddd0ed5c9a75c46b6dR10) to `ament_cmake` makes the timeout trigger.

How can I get the nose test to timeout? from what I've read (`python3 -m nose --help`) there should be a default timeout value of 10 seconds. I have tried adding `--process-timeout=2` to the test call but nothing changed.

**Comment by dirk-thomas** [comment]
I don't think `nose` is capable of what you are expecting. If you call `nosetests test/test_timeout.py` I would expect your example to also hang forever (and that is exactly what ament is calling under the hood). E.g. see http://lists.idyll.org/pipermail/testing-in-python/2011-September/004413.html

**Comment by dhood** [comment]
ok. it surprised me that the same test using the same test framework had different behaviour, but I suppose that's just one of the benefits that comes with choosing `ament_cmake` over `ament_python` packages: that the nose tests get wrapped in the ctest call and any hanging tests will timeout. 
Thanks for your response
